"""add orchestrator_sessions

Revision ID: 6cf6377d8abb
Revises: cb2e6dc947b4
Create Date: 2026-03-04 16:36:06.475370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf6377d8abb'
down_revision: Union[str, Sequence[str], None] = 'cb2e6dc947b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrator_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'WAITING_FOR_APPROVAL', 'COMPLETE', 'FAILED', name='session_status'), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_job_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orchestrator_sessions_created_at', 'orchestrator_sessions', ['created_at'], unique=False)
    op.create_index('ix_orchestrator_sessions_status', 'orchestrator_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orchestrator_sessions_status', table_name='orchestrator_sessions')
    op.drop_index('ix_orchestrator_sessions_created_at', table_name='orchestrator_sessions')
    op.drop_table('orchestrator_sessions')
    # ### end Alembic commands ###
