"""initial_schema_jobs_applications_user_profiles

Revision ID: cb2e6dc947b4
Revises: 
Create Date: 2026-03-03 02:30:32.141357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2e6dc947b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('LINKEDIN', 'INDEED', 'GREENHOUSE', 'LEVER', 'OTHER', name='job_source'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SCORED', 'REVIEWED', 'IGNORED', 'APPLIED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_jobs_source_url')
    )
    op.create_index('ix_jobs_company', 'jobs', ['company'], unique=False)
    op.create_index('ix_jobs_deleted_at', 'jobs', ['deleted_at'], unique=False)
    op.create_index('ix_jobs_source', 'jobs', ['source'], unique=False)
    op.create_index('ix_jobs_status_match_score', 'jobs', ['status', 'match_score'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1000), nullable=True),
    sa.Column('github_url', sa.String(length=1000), nullable=True),
    sa.Column('portfolio_url', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('resume_path', sa.String(length=1000), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('target_titles', sa.Text(), nullable=True),
    sa.Column('target_locations', sa.Text(), nullable=True),
    sa.Column('company_blocklist', sa.Text(), nullable=True),
    sa.Column('target_internships', sa.Boolean(), nullable=False),
    sa.Column('target_new_grad', sa.Boolean(), nullable=False),
    sa.Column('auto_apply_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'FAILED', 'MANUAL_REQUIRED', name='application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('screenshot_path', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ats_system', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_table('applications')
    op.drop_table('user_profiles')
    op.drop_index('ix_jobs_status_match_score', table_name='jobs')
    op.drop_index('ix_jobs_source', table_name='jobs')
    op.drop_index('ix_jobs_deleted_at', table_name='jobs')
    op.drop_index('ix_jobs_company', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
